# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_diann_rcppeigen_hello_world', PACKAGE = 'diann')
}

col_max <- function(quantities, m, n) {
    .Call('_diann_col_max', PACKAGE = 'diann', quantities, m, n)
}

maxlfq_solve <- function(quantities, peptides, samples, margin = -10.0001) {
    .Call('_diann_maxlfq_solve', PACKAGE = 'diann', quantities, peptides, samples, margin)
}

